name: Rust

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: rustup target add x86_64-unknown-linux-musl
      
    - name: Build
      run: cargo build --profile=fast  --target=x86_64-unknown-linux-musl

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
        path: |
          ./target/fast/biliroaming_rust_server
          ./config.json
